### ISSUE TITLE
Randomize bday wishes

### ISSUE THREAD

**Issue by themousepotato** [thealphadollar/salvator#5]
It would be nice if the birthday wish is a random quote from a list.

**Comment by thealphadollar** [comment]
Would you like to work on this? @TheMousePotato

Also don't you think that would be an overkill considering it might come out as showy. Maybe, give the user an option as well to turn this off.

**Comment by TheMousePotato** [comment]
I didn't mean making the text too fancy.  But, it can be slightly different. Option for turning this off is a good resolution tho.

**Comment by thealphadollar** [comment]
@TheMousePotato  You want to work on this?

**Comment by TheMousePotato** [comment]
Not now @thealphadollar :)
