### ISSUE TITLE
Gives ERROR: Failed to download Chromium r609904! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download. when trying to install the module globally using npm

### ISSUE THREAD

**Issue by kryptokinght** [thealphadollar/salvator#9]
Steps to recreate the Error:
1. sudo npm install -g puppeteer-salvator
2. ERROR Occurs(while running the script install.js) , Details below:
> node install.js

ERROR: Failed to download Chromium r609904! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
`{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer-salvator/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/puppeteer-salvator/node_modules/puppeteer/.local-chromium' }`
3. so i try this instead: `echo "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install -g puppeteer-salvator" | sudo sh`
4. INSTALLS successfully after skipping the download of Chromium.
5. But when i run the command `puppeteer-salvator` in the terminal, gives `command not found`.

**Comment by kryptokinght** [comment]
@thealphadollar The thing is puppeteer-salvator is a package but not a command-line package. It can be imported just like other regular npm packages but it cannot be run directly on the terminal. In order to run on the terminal it must contain a special shell-instruction in a file like cli.js. So we need to make it into a cli package and the cli package must have features like entering the password, username, email, setting-up cron jobs directly from the command-line. All this must be setup before executing on the cli. I have started to read about cli packages and if you give me the green signal, i can submit a PR on this.

**Comment by thealphadollar** [comment]
Okay, sure.

Go ahead!

**Comment by kryptokinght** [comment]
On it, will submit in a PR in a day or two

**Comment by kryptokinght** [comment]
fixed by #23 . This issue can be closed
